name: Run Job

on:
  workflow_run:
    workflows: [ "Lint and Test" ]
    types:
      - completed

jobs:
  run-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      FRANCE_TRAVAIL_CLIENT_ID: ${{ secrets.FRANCE_TRAVAIL_CLIENT_ID }}
      FRANCE_TRAVAIL_CLIENT_SECRET: ${{ secrets.FRANCE_TRAVAIL_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run with Docker Compose
        run: |
          echo "FRANCE_TRAVAIL_CLIENT_ID=$FRANCE_TRAVAIL_CLIENT_ID" >> .env
          echo "FRANCE_TRAVAIL_CLIENT_SECRET=$FRANCE_TRAVAIL_CLIENT_SECRET" >> .env
          docker compose up --build --abort-on-container-exit

      - name: Upload CSV output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: job-results
          path: data/*.csv